Repository KUIT-AGARANG/Agarang_Frontend, pull requests merged in 2024-08, with the labels that each got.

#71 [FEAT]: 로그인 액티비티, 첫 화면 추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/myapplication/LoginActivity.kt
  app/src/main/java/com/example/myapplication/LoginStartFragment.kt
  app/src/main/res/drawable/ic_login_agarang.xml
  app/src/main/res/drawable/ic_login_google.png
  app/src/main/res/drawable/ic_login_kakao.png
  app/src/main/res/drawable/login_agarang.png
  app/src/main/res/drawable/login_agarang_text_img.png
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/fragment_login_start.xml
  icon/login_agarang.png
Labels: 🌈feat

#67 태명, 출산 예정일 UI / 추억 공유 API 초기
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/myapplication/Data/Request/MemoryRequest.kt
  app/src/main/java/com/example/myapplication/Data/Response/MemoryResponse.kt
  app/src/main/java/com/example/myapplication/Login/BirthNameFragment.kt
  app/src/main/java/com/example/myapplication/Login/DueDateFragment.kt
  app/src/main/java/com/example/myapplication/MainActivity.kt
  app/src/main/java/com/example/myapplication/Memory/PicAssociationFragment.kt
  app/src/main/java/com/example/myapplication/Memory/SelectInstrumentFragment.kt
  app/src/main/java/com/example/myapplication/Retrofit/MemoryIF.kt
  app/src/main/java/com/example/myapplication/Setting/ChildInfoChangeFragment.kt
  app/src/main/res/drawable/edit_texxt_background.xml
  app/src/main/res/drawable/ic_progress_ball.xml
  app/src/main/res/layout/fragment_birth_name.xml
  app/src/main/res/layout/fragment_calendar.xml
  app/src/main/res/layout/fragment_due_date.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_pic_association.xml
Labels: bug, enhancement

#72 [Feat]: 다이어리 일 조회 API 연동 완료, 로그인 코드 입력_1 fragment 생성
  .idea/deploymentTargetSelector.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/myapplication/Data/Response/DiaryDayResponse.kt
  app/src/main/java/com/example/myapplication/Diary/DiaryCardEditFragment.kt
  app/src/main/java/com/example/myapplication/Diary/DiaryMainDayData.kt
  app/src/main/java/com/example/myapplication/Diary/DiaryMainDayFragment.kt
  app/src/main/java/com/example/myapplication/Home/HomeFragment.kt
  app/src/main/java/com/example/myapplication/Login/LoginActivity.kt
  app/src/main/java/com/example/myapplication/Login/LoginCode1Fragment.kt
  app/src/main/java/com/example/myapplication/Login/LoginStartFragment.kt
  app/src/main/java/com/example/myapplication/LoginStartFragment.kt
  app/src/main/java/com/example/myapplication/Memory/DeepQuestionFragment.kt
  app/src/main/java/com/example/myapplication/Retrofit/DiaryIF.kt
  app/src/main/java/com/example/myapplication/Retrofit/MemoryIF.kt
  app/src/main/res/drawable/ic_code_no.xml
  app/src/main/res/drawable/ic_code_yes.xml
  app/src/main/res/drawable/ic_login_agarang.xml
  app/src/main/res/drawable/ic_login_code_button.xml
  app/src/main/res/layout/fragment_login_code1.xml
  icon/ic_code_no.svg
  icon/ic_code_yes.svg
  icon/ic_login_code_button.svg
Labels: 🌈feat, 🎨Design

#74 추억공유 UI 수정
  .idea/appInsightsSettings.xml
  app/src/main/java/com/example/myapplication/Memory/DeepQuestionFragment.kt
  app/src/main/java/com/example/myapplication/Memory/PicAssociationFragment.kt
  app/src/main/res/layout/fragment_picture.xml
Labels: 🎨Design

#78 다이어리 즐겨찾기 설정 API, 음악 선택사항 API, etc
  app/build.gradle.kts
  app/src/main/java/com/example/myapplication/Data/Request/MemoryRequest.kt
  app/src/main/java/com/example/myapplication/Data/Response/DiaryBookmarkResponse.kt
  app/src/main/java/com/example/myapplication/Data/Response/MemoryResponse.kt
  app/src/main/java/com/example/myapplication/Diary/CardViewAdapter.kt
  app/src/main/java/com/example/myapplication/Diary/DiaryMainCardFragment.kt
  app/src/main/java/com/example/myapplication/Memory/DeepQuestionFragment.kt
  app/src/main/java/com/example/myapplication/Memory/FinFragment.kt
  app/src/main/java/com/example/myapplication/Memory/GenreAdapter.kt
  app/src/main/java/com/example/myapplication/Memory/InstrumentData.kt
  app/src/main/java/com/example/myapplication/Memory/MemoryMainActivity.kt
  app/src/main/java/com/example/myapplication/Memory/MoodAdapter.kt
  app/src/main/java/com/example/myapplication/Memory/PicAssociationFragment.kt
  app/src/main/java/com/example/myapplication/Memory/SelectGenreFragment.kt
  app/src/main/java/com/example/myapplication/Memory/SelectInstrumentFragment.kt
  app/src/main/java/com/example/myapplication/Memory/SelectMoodFragment.kt
  app/src/main/java/com/example/myapplication/Memory/SelectSpeedFragment.kt
  app/src/main/java/com/example/myapplication/Retrofit/DiaryIF.kt
  app/src/main/java/com/example/myapplication/Retrofit/MemoryIF.kt
  app/src/main/java/com/example/myapplication/SharedViewModel.kt
  app/src/main/res/layout/activity_login.xml
Labels: 🌈feat

#83 fix: 홈 관련 버그 수정
  app/src/main/java/com/example/myapplication/Home/HomeFragment.kt
  app/src/main/java/com/example/myapplication/Memory/FinFragment.kt
  app/src/main/java/com/example/myapplication/Memory/SelectGenreFragment.kt
  app/src/main/java/com/example/myapplication/Memory/SelectInstrumentFragment.kt
  app/src/main/java/com/example/myapplication/Memory/SelectMoodFragment.kt
  app/src/main/java/com/example/myapplication/Memory/SelectSpeedFragment.kt
  app/src/main/java/com/example/myapplication/Setting/ChildInfoChangeFragment.kt
  app/src/main/java/com/example/myapplication/Setting/HomeSettingFragment.kt
  app/src/main/java/com/example/myapplication/SharedViewModel.kt
Labels: 🔨fix

#79 [Feat]: 카드 조회 API 서버연동 완료
  app/src/main/java/com/example/myapplication/Diary/CardViewAdapter.kt
  app/src/main/java/com/example/myapplication/Diary/DateAdapter.kt
  app/src/main/java/com/example/myapplication/Diary/DiaryMainCardFragment.kt
  app/src/main/java/com/example/myapplication/Diary/DiaryMainDayData.kt
  app/src/main/java/com/example/myapplication/Diary/DiaryMainDayFragment.kt
  app/src/main/java/com/example/myapplication/Retrofit/DiaryIF.kt
Labels: 🌈feat, ❗Breaking Change❗

#87 충돌 및 빌드 오류 해결 필요
  .idea/deploymentTargetSelector.xml
  app/src/main/java/com/example/myapplication/Data/Response/PlaylistResponse.kt
  app/src/main/java/com/example/myapplication/Diary/DiaryMainCardFragment.kt
  app/src/main/java/com/example/myapplication/Home/HomeFragment.kt
  app/src/main/java/com/example/myapplication/Music/MusicAlbumFragment.kt
  app/src/main/java/com/example/myapplication/Music/MusicFragment.kt
  app/src/main/java/com/example/myapplication/Music/MusicMainAdapter.kt
  app/src/main/java/com/example/myapplication/Music/MusicMainData.kt
  app/src/main/java/com/example/myapplication/Retrofit/PlaylistIF.kt
  app/src/main/java/com/example/myapplication/Setting/HomeSettingFragment.kt
  app/src/main/res/layout/music_item.xml
Labels: 🔨fix

#88 [FIX}: 홈 메인, 홈 설정 API 수정
  .idea/deploymentTargetSelector.xml
  app/src/main/java/com/example/myapplication/Home/HomeFragment.kt
  app/src/main/java/com/example/myapplication/Login/LoginActivity.kt
  app/src/main/java/com/example/myapplication/Setting/HomeSettingFragment.kt
Labels: bug, 🔨fix

#93 [FIX]: 캐릭터 조회 부분 API 연동 중 버그 수정
  app/src/main/java/com/example/myapplication/Data/Response/HomeChildResponse.kt
  app/src/main/java/com/example/myapplication/Login/LoginStartFragment.kt
  app/src/main/java/com/example/myapplication/Retrofit/HomeIF.kt
  app/src/main/java/com/example/myapplication/Setting/ChangeChar2Adapter.kt
  app/src/main/java/com/example/myapplication/Setting/ChangeChar2Fragment.kt
  app/src/main/java/com/example/myapplication/Setting/ChildInfoChangeFragment.kt
  app/src/main/java/com/example/myapplication/Setting/HomeSettingFragment.kt
Labels: 🔨fix

#101 [FEAT]: 아이정보 조회 API 수정, 아이정보 수정 API 연동
  app/src/main/java/com/example/myapplication/Data/Request/ChildInfoUpdateRequest.kt
  app/src/main/java/com/example/myapplication/Data/Response/HomeChildResponse.kt
  app/src/main/java/com/example/myapplication/Data/Response/HomeChildUpdateResponse.kt
  app/src/main/java/com/example/myapplication/Retrofit/HomeIF.kt
  app/src/main/java/com/example/myapplication/Setting/ChangeCharFragment.kt
  app/src/main/java/com/example/myapplication/Setting/ChildInfoChangeFragment.kt
  app/src/main/res/layout/fragment_child_info_change.xml
Labels: 🌈feat, 🔨fix

#102 [FEAT]: 온보딩 구현 완료
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/myapplication/OnboardingActivity.kt
  app/src/main/java/com/example/myapplication/OnboardingFirstFragment.kt
  app/src/main/java/com/example/myapplication/OnboardingFourthFragment.kt
  app/src/main/java/com/example/myapplication/OnboardingLoginFragment.kt
  app/src/main/java/com/example/myapplication/OnboardingSecondFragment.kt
  app/src/main/java/com/example/myapplication/OnboardingThirdFragment.kt
  app/src/main/java/com/example/myapplication/RegisterPagerAdapter.kt
  app/src/main/java/com/example/myapplication/SplashActivity.kt
  app/src/main/res/drawable/onboarding_1.png
  app/src/main/res/drawable/onboarding_2.png
  app/src/main/res/drawable/onboarding_3.png
  app/src/main/res/drawable/onboarding_4.png
  app/src/main/res/drawable/onboarding_5.png
  app/src/main/res/drawable/onboarding_start.png
  app/src/main/res/drawable/splash_logo.png
  app/src/main/res/layout/activity_onboarding.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/fragment_onboarding_first.xml
  app/src/main/res/layout/fragment_onboarding_fourth.xml
  app/src/main/res/layout/fragment_onboarding_login.xml
  app/src/main/res/layout/fragment_onboarding_second.xml
  app/src/main/res/layout/fragment_onboarding_third.xml
  icon/splash_logo.svg
Labels: 🌈feat
